# Create the open cluster file for latex, to include in the paper

I compiled the open cluster catalog here: https://github.com/ageller/compileOCs , 

I think I will include all the columns in the clean file


Note: masses assume a mean stellar mass of 0.5 Msun (for literature sources that provide number of stars)

Note: rhm is a bit tricky.  Maybe I should just call this a radius estimate?  If the rc is provided, I convert this to rhm using a Plummer model, others provide a diameter measurement, which I divide by two.

In [9]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 500)

from astropy import units, constants
from astropy.coordinates import SkyCoord

import matplotlib.pyplot as plt
%matplotlib inline

In [19]:
OC_df = pd.read_csv('OCcompiled_clean.csv')
OC_df

,ID,RA,Dec,ID_Simbad,ID_MWSC,ID_WEBDA,ID_Piskunov,ID_Kharchenko,ID_Salaris,ID_vandenBergh,ID_Cantat-Gaudin,ID_Lynga,dist[pc],err_dist[pc],N_dist[pc],age[Myr],err_age[Myr],N_age[Myr],[Fe/H],err_[Fe/H],N_[Fe/H],mass[Msun],err_mass[Msun],N_mass[Msun],rgc[pc],err_rgc[pc],N_rgc[pc],rhm[pc],err_rhm[pc],N_rhm[pc]
0,[KPS2012]_MWSC_4688,23 51 54.000,-86 43 12.000,[KPS2012]_MWSC_4688,MWSC_4688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1336.0,0.0,1.0,2454.708916,0.0,1.0,NaN,NaN,NaN,28.5,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,[KPS2012]_MWSC_5684,12 53 43.000,-86 38 54.000,NaN,MWSC_5684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1432.0,0.0,1.0,1513.561248,0.0,1.0,NaN,NaN,NaN,26.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,[KPS2012]_MWSC_5692,17 47 20.000,-86 36 36.000,NaN,MWSC_5692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1555.0,0.0,1.0,851.138038,0.0,1.0,NaN,NaN,NaN,14.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,[KPS2012]_MWSC_4005,00 11 28.000,-85 28 48.000,[KPS2012]_MWSC_4005,MWSC_4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1159.0,0.0,1.0,2371.373706,0.0,1.0,NaN,NaN,NaN,21.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,[KPS2012]_MWSC_4176,14 27 18.000,-85 25 12.000,[KPS2012]_MWSC_4176,MWSC_4176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1093.0,0.0,1.0,2065.380156,0.0,1.0,NaN,NaN,NaN,77.5,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3348,C_0845-527,08 46 27.706,-52 54 03.240,C_0845-527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,vdBergh-Hagen_52,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3349,Av-hunter_1,23 37 13.898,48 24 36.756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Av-hunter_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3350,Latysev_1,02 52 27.202,27 28 16.068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Latysev_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3351,Cl_Basel_11,07 17 06.074,-13 57 26.100,Cl_Basel_11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Basel_11,NaN,NaN,NaN,316.227766,0.0,1.0,NaN,NaN,NaN,15.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3352,Cl_Loden_336,11 19 50.021,-58 51 26.028,Cl_Loden_336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Loden_336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
OC_df.rename(columns = {'RA':'RA[hr]','Dec':'Dec[deg]','rhm[pc]':'r[pc]','err_rhm[pc]':'err_r[pc]','N_rhm[pc]':'N_r[pc]'}, inplace=True)
OC_df.replace('_', ' ', regex=True, inplace=True)
OC_df.round(1, inplace_True)
OC_df

NameError: name 'inplace_True' is not defined

In [29]:
OC_df.to_latex('OCtable.tex',na_rep='nodata', index=False)